name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please search existing issues before submitting to avoid duplicates.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched the [existing issues](https://github.com/looplj/axonhub/issues) and this bug has not been reported
          required: true
        - label: I have read the [documentation](https://github.com/looplj/axonhub#readme)
          required: true
        - label: I am using the latest version of AxonHub
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - macOS
        - Windows
        - Docker
        - Other
    validations:
      required: true

  - type: input
    id: axonhub-version
    attributes:
      label: AxonHub Version
      description: What version of AxonHub are you running?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: dropdown
    id: channel-type
    attributes:
      label: Channel Type
      description: Which channel type is affected? (if applicable)
      options:
        - N/A
        - OpenAI
        - Anthropic
        - Google Gemini
        - DeepSeek
        - Custom/Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (please remove sensitive information)
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem here
